CREATE TABLE users (
    id UUID PRIMARY KEY,
    user_name VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    created_tsp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
